export const TIMER_SET_TIMER = 'TIMER_SET_TIMER';
export const TIMER_RESET_TIMER = 'TIMER_RESET_TIMER';
export const TIMER_PLAY_TIMER = 'TIMER_PLAY_TIMER';
export const TIMER_PAUSE_TIMER = 'TIMER_PAUSE_TIMER';
export const TIMER_SET_SPEED = 'TIMER_SET_SPEED';